name: MineloadPlugin
version: 0.0.7
description: Generates Minecraft server performace in XML format.

author: Timatooth
website: https://github.com/Timatooth/
softdepend: [JSONAPI, LWC]
main: com.timatooth.mineload.MineloadPlugin