name: MineloadPlugin
version: 0.0.3
description: Provide performance data access to web or other application.

author: timatooth_teeth
website: http://forgottendynasties.net
softdepend: [JSONAPI, LWC]
main: com.gmail.timaaarrreee.mineload.MineloadPlugin