name: MineloadPlugin
version: 0.0.5
description: Generates Minecraft server performace in XML format.

author: timatooth
website: http://github.com/timatooth
softdepend: [JSONAPI, LWC]
main: com.timatooth.mineload.MineloadPlugin